apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: dev
data:
  ME_CONFIG_MONGODB_SERVER: my-mongo
  ME_CONFIG_MONGODB_PORT: "27017"

  # Mongo auth (THIS FIXES CRASHLOOP)
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # Login for mongo-express website
  ME_CONFIG_BASICAUTH_USERNAME: admin
  ME_CONFIG_BASICAUTH_PASSWORD: admin
