apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: faiza22/mongo-express-exam:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: mongo-express-config
            - secretRef:
                name: mongo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: dev
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
