apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mongo
  template:
    metadata:
      labels:
        app: my-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongo
  namespace: dev
spec:
  selector:
    app: my-mongo
  ports:
    - port: 27017
