- name: Configure EC2 Server
  hosts: ec2
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # ==============================
    # CI/CD REQUIRED ADDITIONS START
    # ==============================

    - name: Install git, curl, conntrack
      apt:
        name:
          - git
          - curl
          - conntrack
        state: present

    - name: Install kubectl
      shell: |
        set -e
        if ! command -v kubectl >/dev/null 2>&1; then
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
          apt-get update -y
          apt-get install -y kubectl
        fi
      args:
        executable: /bin/bash

    - name: Install Minikube
      shell: |
        set -e
        if ! command -v minikube >/dev/null 2>&1; then
          curl -fsSLo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x /usr/local/bin/minikube
        fi
      args:
        executable: /bin/bash

    - name: Start Minikube (docker driver)
      # become_user: ubuntu
      shell: |
        set -e
        minikube status >/dev/null 2>&1 || sudo minikube start --driver=docker
      args:
        executable: /bin/bash

    - name: Clone repo on EC2
      become_user: ubuntu
      git:
        repo: "https://github.com/FaizaAslam013/Devops-Mids-Exam.git"
        dest: "/home/ubuntu/Devops-Mids-Exam"
        version: "master"
        update: yes

    - name: Apply Kubernetes manifests
      become_user: ubuntu
      shell: kubectl apply -f /home/ubuntu/Devops-Mids-Exam/k8s
      args:
        executable: /bin/bash
